/// Catálogo de iconos Material disponibles, identificados por nombre.
///
/// El renderizado a `IconData` se resuelve aparte: aquí solo se conserva el
/// nombre del icono y su etiqueta en español.
class IconItem {
  final String name;
  final String label;
  const IconItem(this.name, this.label);
}

abstract final class AppIcons {
  static const List<IconItem> animalIcons = [
    IconItem('pets', 'Mascotas'),
    IconItem('cruelty_free', 'Cruelty Free'),
    IconItem('pest_control', 'Control de Plagas'),
    IconItem('bug_report', 'Reporte de Insecto'),
    IconItem('park', 'Parque'),
    IconItem('forest', 'Bosque'),
    IconItem('grass', 'Hierba'),
    IconItem('nature', 'Naturaleza'),
    IconItem('eco', 'Ecológico'),
    IconItem('spa', 'Spa'),
    IconItem('yard', 'Jardín'),
    IconItem('water', 'Agua'),
    IconItem('water_drop', 'Gota de Agua'),
    IconItem('waves', 'Olas'),
    IconItem('waterfall', 'Cascada'),
    IconItem('waterfront', 'Orilla'),
    IconItem('wb_sunny', 'Sol'),
    IconItem('nights_stay', 'Noche'),
    IconItem('wb_cloudy', 'Nublado'),
    IconItem('cloud', 'Nube'),
    IconItem('filter_drama', 'Drama'),
    IconItem('thunderstorm', 'Tormenta'),
    IconItem('ac_unit', 'Nieve'),
    IconItem('beach_access', 'Playa'),
    IconItem('castle', 'Castillo'),
    IconItem('villa', 'Villa'),
    IconItem('house', 'Casa'),
    IconItem('home', 'Hogar'),
    IconItem('cottage', 'Casa de Campo'),
    IconItem('apartment', 'Apartamento'),
    IconItem('holiday_village', 'Aldea Turística'),
    IconItem('location_city', 'Ciudad'),
    IconItem('terrain', 'Terreno'),
    IconItem('landscape', 'Paisaje'),
    IconItem('photo_camera', 'Cámara'),
    IconItem('photo_library', 'Galería'),
    IconItem('camera_roll', 'Rollo de Cámara'),
    IconItem('image', 'Imagen'),
    IconItem('wallpaper', 'Fondo de Pantalla'),
    IconItem('filter_vintage', 'Filtro Vintage'),
    IconItem('local_florist', 'Floristería'),
    IconItem('local_parking', 'Estacionamiento'),
    IconItem('directions_car', 'Coche'),
    IconItem('directions_walk', 'Caminar'),
    IconItem('pedestrian', 'Peatón'),
    IconItem('farm', 'Granja'),
    IconItem('agriculture', 'Agricultura'),
    IconItem('compost', 'Composta'),
    IconItem('tractor', 'Tractor'),
    IconItem('pest_control_rodent', 'Roedores'),
    IconItem('shower', 'Ducha'),
    IconItem('bathtub', 'Bañera'),
    IconItem('hot_tub', 'Jacuzzi'),
    IconItem('room_service', 'Servicio de Habitación'),
    IconItem('restaurant', 'Restaurante'),
    IconItem('local_cafe', 'Cafetería'),
    IconItem('local_bar', 'Bar'),
    IconItem('local_dining', 'Comida'),
    IconItem('icecream', 'Helado'),
    IconItem('cookie', 'Galleta'),
    IconItem('candy', 'Dulces'),
    IconItem('lunch_dining', 'Almuerzo'),
    IconItem('breakfast_dining', 'Desayuno'),
    IconItem('dinner_dining', 'Cena'),
    IconItem('bakery_dining', 'Panadería'),
    IconItem('ramen_dining', 'Ramen'),
    IconItem('set_meal', 'Comida Preparada'),
    IconItem('local_grocery_store', 'Tienda de Abarrotes'),
    IconItem('storefront', 'Tienda'),
    IconItem('shopping_bag', 'Bolsa de Compras'),
    IconItem('shopping_cart', 'Carrito'),
    IconItem('point_of_sale', 'Punto de Venta'),
    IconItem('qr_code', 'Código QR'),
    IconItem('credit_card', 'Tarjeta de Crédito'),
    IconItem('payments', 'Pagos'),
    IconItem('account_balance', 'Cuenta Bancaria'),
    IconItem('savings', 'Ahorros'),
    IconItem('trending_up', 'Tendencia'),
    IconItem('show_chart', 'Gráfico'),
    IconItem('pie_chart', 'Gráfico de Pie'),
    IconItem('bar_chart', 'Gráfico de Barras'),
    IconItem('timeline', 'Línea de Tiempo'),
    IconItem('calendar_month', 'Calendario'),
    IconItem('event', 'Evento'),
    IconItem('celebration', 'Celebración'),
    IconItem('party_mode', 'Modo Fiesta'),
    IconItem('card_giftcard', 'Regalo'),
    IconItem('favorite', 'Favorito'),
    IconItem('star', 'Estrella'),
    IconItem('thumb_up', 'Me gusta'),
    IconItem('sentiment_satisfied', 'Satisfecho'),
    IconItem('mood', 'Estado de Ánimo'),
    IconItem('sentiment_very_satisfied', 'Muy Satisfecho'),
    IconItem('sentiment_dissatisfied', 'Insatisfecho'),
    IconItem('sentiment_neutral', 'Neutral'),
    IconItem('emoji_emotions', 'Emociones'),
    IconItem('emoji_events', 'Eventos'),
    IconItem('psychology', 'Psicología'),
    IconItem('self_improvement', 'Automejora'),
    IconItem('accessibility_new', 'Accesibilidad'),
    IconItem('accessibility', 'Accesible'),
    IconItem('accessible', 'Accesible'),
    IconItem('videocam', 'Videocámara'),
    IconItem('movie', 'Película'),
    IconItem('music_note', 'Música'),
    IconItem('headphones', 'Auriculares'),
    IconItem('headset', 'Auricular'),
    IconItem('speaker', 'Altavoz'),
    IconItem('radio', 'Radio'),
    IconItem('tv', 'Televisión'),
    IconItem('smartphone', 'Teléfono'),
    IconItem('laptop', 'Laptop'),
    IconItem('computer', 'Computadora'),
    IconItem('tablet', 'Tableta'),
    IconItem('gamepad', 'Control de Juego'),
    IconItem('sports', 'Deportes'),
  ];

  static const List<IconItem> sportsIcons = [
    IconItem('sports_soccer', 'Fútbol'),
    IconItem('sports_basketball', 'Baloncesto'),
    IconItem('sports_volleyball', 'Voleibol'),
    IconItem('sports_football', 'Fútbol Americano'),
    IconItem('sports_baseball', 'Béisbol'),
    IconItem('sports_cricket', 'Críquet'),
    IconItem('sports_tennis', 'Tenis'),
    IconItem('sports_handball', 'Balonmano'),
    IconItem('sports_hockey', 'Hockey'),
    IconItem('sports_golf', 'Golf'),
    IconItem('pool', 'Natación'),
    IconItem('fitness_center', 'Gimnasio'),
    IconItem('directions_run', 'Atletismo'),
    IconItem('directions_bike', 'Ciclismo'),
    IconItem('skateboarding', 'Skateboarding'),
    IconItem('snowboarding', 'Snowboard'),
    IconItem('surfing', 'Surf'),
    IconItem('kayaking', 'Kayak'),
    IconItem('sailing', 'Vela'),
    IconItem('rowing', 'Remo'),
    IconItem('boxing', 'Boxeo'),
    IconItem('martial_arts', 'Artes Marciales'),
    IconItem('wrestling', 'Lucha'),
    IconItem('gymnastics', 'Gimnasia'),
    IconItem('badminton', 'Bádminton'),
    IconItem('table_tennis', 'Tenis de Mesa'),
    IconItem('squash', 'Squash'),
    IconItem('racquet', 'Ráquetbol'),
    IconItem('bowling', 'Bolos'),
    IconItem('curling', 'Curling'),
    IconItem('luge', 'Luge'),
    IconItem('bobsleigh', 'Bobsleigh'),
    IconItem('skiing', 'Esquí'),
    IconItem('sailing', 'Navegación'),
    IconItem('phishing', 'Pesca'),
    IconItem('rock_climbing', 'Escalada'),
    IconItem('hiking', 'Senderismo'),
    IconItem('camping', 'Camping'),
    IconItem('kite_surfing', 'Kitesurf'),
    IconItem('windsurfing', 'Windsurf'),
    IconItem('scuba_diving', 'Buceo'),
    IconItem('snorkeling', 'Snorkeling'),
    IconItem('archery', 'Tiro con Arco'),
    IconItem('fencing', 'Esgrima'),
    IconItem('shooting', 'Tiro Deportivo'),
    IconItem('weightlifting', 'Halterofilia'),
    IconItem('roller_skating', 'Patinaje'),
    IconItem('inline_skating', 'Patinaje Inline'),
    IconItem('ice_skating', 'Patinaje sobre Hielo'),
    IconItem('motor_sports', 'Deportes de Motor'),
    IconItem('sports_motorsports', 'Motocross'),
    IconItem('formula_1', 'Fórmula 1'),
    IconItem('nascar', 'NASCAR'),
    IconItem('rallying', 'Rally'),
    IconItem('equestrian', 'Equitación'),
    IconItem('polo', 'Polo'),
    IconItem('rugby', 'Rugby'),
    IconItem('lacrosse', 'Lacrosse'),
    IconItem('field_hockey', 'Hockey Campo'),
    IconItem('water_polo', 'Waterpolo'),
    IconItem('diving', 'Salto'),
    IconItem('synchronized_swimming', 'Natación Sincronizada'),
    IconItem('triathlon', 'Triatlón'),
    IconItem('pentathlon', 'Pentatlón'),
    IconItem('decathlon', 'Decatlón'),
    IconItem('crossword', 'Ajedrez'),
    IconItem('casino', 'Apuestas'),
  ];

  static final List<String> sportsIconNames =
      sportsIcons.map((icon) => icon.name).toList();

  static final Map<String, String> sportsIconMap = {
    for (final icon in sportsIcons) icon.name: icon.label,
  };

  static final List<String> animalIconNames =
      animalIcons.map((icon) => icon.name).toList();

  static final Map<String, String> animalIconMap = {
    for (final icon in animalIcons) icon.name: icon.label,
  };
}
